const JWT_SECRET_KEY = 'getyourride2024';

const GEOAPIFY_API_KEY = "API_KEY";

const RAZORPAY_API_KEY = "API_KEY";
const RAZORPAY_API_SECRET = "API_SECRET";

// From Email sended by customer
const SEND_GMAIL_ADDRESS = "SEND_GMAIL_ADDRESS";
// Send Email App Password
const SEND_GMAIL_PASSWORD = "SENG_GMAIL_APP_PASSWORD";

// Where Email receivered with customer details
const RECEIVER_GMAIL_ADDRESS = "RECEIVE_GMAIL_ADDRESS";

module.exports = {
    JWT_SECRET_KEY,
    GEOAPIFY_API_KEY,
    RAZORPAY_API_KEY,
    RAZORPAY_API_SECRET,
    SEND_GMAIL_ADDRESS,
    SEND_GMAIL_PASSWORD,
    RECEIVER_GMAIL_ADDRESS
}